checkpoints:
  dirpath: null
  filename: best-{epoch:02d}-{val_loss:.4f}
  mode: min
  monitor: val_loss
  save_last: true
  save_top_k: 10
comet_logger:
  api_key: 8ONjCXJ1ogsqG1UxQzKxYn7tz
  experiment_name: null
  project_name: multimodal-jets
  save_dir: /home/df630/Multimodal-Bridges/experiments/results/comet
  workspace: dfaroughy
data:
  batch_size: 1024
  dim_context_continuous: 0
  dim_context_discrete: 0
  dim_continuous: 3
  dim_discrete: 1
  max_num_particles: 128
  min_num_particles: 0
  modality: hybrid
  num_jets: 100000
  num_workers: 0
  pin_memory: false
  source_name: GaussNoise
  source_preprocess_continuous: null
  source_preprocess_discrete: tokenize
  source_test_path: null
  source_train_path: null
  split_ratios:
  - 0.7
  - 0.3
  target_name: AspenOpenJets
  target_preprocess_continuous: standardize
  target_preprocess_discrete: tokenize
  target_test_path:
  - /home/df630/CMB/data/AOJ/2016H_job8.h5
  - /home/df630/CMB/data/AOJ/2016H_job9.h5
  target_train_path:
  - /home/df630/CMB/data/AOJ/2016H_job0.h5
  - /home/df630/CMB/data/AOJ/2016H_job1.h5
  - /home/df630/CMB/data/AOJ/2016H_job2.h5
  - /home/df630/CMB/data/AOJ/2016H_job3.h5
  - /home/df630/CMB/data/AOJ/2016H_job4.h5
  - /home/df630/CMB/data/AOJ/2016H_job5.h5
  - /home/df630/CMB/data/AOJ/2016H_job6.h5
  - /home/df630/CMB/data/AOJ/2016H_job7.h5
  vocab_size: 8
  vocab_size_context: 0
encoder:
  dim_emb_augment_continuous: 0
  dim_emb_augment_discrete: 0
  dim_emb_context_continuous: 0
  dim_emb_context_discrete: 0
  dim_emb_continuous: 16
  dim_emb_discrete: 16
  dim_emb_time: 32
  dim_hidden_glob: 32
  dim_hidden_local: 128
  dropout: 0.2
  embed_type_augment_continuous: null
  embed_type_augment_discrete: null
  embed_type_context_continuous: null
  embed_type_context_discrete: null
  embed_type_continuous: Linear
  embed_type_discrete: LookupTable
  embed_type_time: SinusoidalPositionalEncoding
  name: MultiModalEPiC
  num_blocks: 12
  skip_connection: true
model:
  bridge_continuous: LinearUniformBridge
  bridge_discrete: TelegraphBridge
  gamma: 0.125
  loss_weights: learnable
  num_timesteps: 200
  sigma: 0.0001
  time_eps: 0.0001
trainer:
  gradient_clip_val: 1.0
  max_epochs: 100
  optimizer_name: AdamW
  optimizer_params:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0002
    weight_decay: 5.0e-05
  scheduler_name: CosineAnnealingLR
  scheduler_params:
    T_max: 100
    eta_min: 1.0e-05
    last_epoch: -1
