config: !!python/object:utils.Configs
  data: !!python/object:utils.Configs
    dim: !!python/object:utils.Configs
      context_continuous: 0
      context_discrete: 0
      features_continuous: 3
      features_discrete: 1
    source: !!python/object:utils.Configs
      name: GaussNoise
      params: !!python/object:utils.Configs
        max_num_particles: 128
        min_num_particles: 0
        scale: 1.0
      path: null
      preprocess: !!python/object:utils.Configs
        continuous: null
        discrete: tokens
        stats: null
    target: !!python/object:utils.Configs
      name: AspenOpenJets
      params: !!python/object:utils.Configs
        max_num_particles: 128
        min_num_particles: 0
      path:
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job0.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job1.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job2.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job3.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job4.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job5.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job6.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job7.h5
        - /pscratch/sd/d/dfarough/aoj/cernbox.cern.ch/remote.php/dav/public-files/r2Rw4sa1nROtsSl/2016H_job8.h5
      preprocess: !!python/object:utils.Configs
        continuous: standardize
        discrete: tokens
        stats:
          max:
          - 1045.0
          - 1.1317514181137085
          - 1.0864198207855225
          mean:
          - 7.47517728805542
          - 0.00039798638317734003
          - 0.000249955483013764
          min:
          - 0.0
          - -1.1116657257080078
          - -1.1444804668426514
          std:
          - 19.519119262695312
          - 0.252874493598938
          - 0.25943297147750854
    vocab_size: !!python/object:utils.Configs
      context: 0
      features: 8
  dynamics: !!python/object:utils.Configs
    bridge_continuous: LinearUniformBridge
    bridge_discrete: TelegraphBridge
    params: !!python/object:utils.Configs
      gamma: 0.125
      sigma: 0.0001
  experiment: !!python/object:utils.Configs
    name: GaussNoise_to_AspenOpenJets_MultiModalEPiC_2024.12.26_08h11_1177
    run_name: aoj_training
    type: multimodal
    workdir: /pscratch/sd/d/dfarough/CMB/results/aoj
  model: !!python/object:utils.Configs
    activation: SELU
    add_discrete_head: true
    dim: !!python/object:utils.Configs
      emb_context_continuous: 0
      emb_context_discrete: 0
      emb_features_continuous: 16
      emb_features_discrete: 16
      emb_time: 16
      hidden_glob: 16
      hidden_local: 128
    dropout: 0.1
    embedding: !!python/object:utils.Configs
      context_continuous: null
      context_discrete: null
      features_continuous: Linear
      features_discrete: Embedding
      time: SinusoidalPositionalEncoding
    name: MultiModalEPiC
    num_blocks: 10
    skip_connection: true
  pipeline: !!python/object:utils.Configs
    method: EulerLeapingSolver
    num_timesteps: 1000
    time_eps: 0.0001
  train: !!python/object:utils.Configs
    batch_size: 1024
    data_split_frac:
    - 0.8
    - 0.2
    - 0.0
    epochs: 100
    optimizer: !!python/object:utils.Configs
      name: AdamW
      params: !!python/object:utils.Configs
        amsgrad: false
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        lr: 0.001
        weight_decay: 5.0e-05
    scheduler: !!python/object:utils.Configs
      name: CosineAnnealingLR
      params: !!python/object:utils.Configs
        T_max: 100
        eta_min: 0.0001
        last_epoch: -1
